apiVersion: v1
kind: Secret #comunichiamo a kubernetes che questo file contiene dati sensibili. Lui li prenderà e li salverà in formato crittografato
metadata:
  name: postgres-secret
  namespace: default
type: Opaque #indica a k3s che questo è un segreto generico (una semplice coppia chiave-valore)
stringData: #ci permette di scrivere la password in testo normale qui nel file yaml, ma k3s la convertirà in codice illeggibile (base64) quando salverà.
  POSTGRES_PASSWORD: "MiaPasswordSuperSegreta123!"
