#le parentesi quadre creano un gruppo di server. qui stiamo creando il gruppo per i capi
#vm1 è il nome che scegliamo noi
[master]
vm1 ansible_host=192.168.0.53 ansible_user=ale

#gruppo per gli operai
#vm2 è il nome che scegliamo noi
[workers]
vm2 ansible_host=192.168.0.234 ansible_user=ale_12

#:children significa che questo gruppo contiene altri gruppi, cluster è il nome
#master e workers sono i gruppi che inseriamo all'interno. Se diciamo ad ansible di colpire cluster, lui colpirà in automatico sia vm1 che vm2
[cluster:children]
master
workers
